[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rasm"
version = "1.0.0"
description = "Rasm is a text processing utility for converting Arabic-scripted text to a completely dediacritised skeleton"
readme = "README.md"
authors = [{ name = "Alicia González Martínez", email = "aliciagm85+rasm@google.com" },
           { name = "Thomas Milo"}]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Natural Language :: Arabic",
    "Natural Language :: Persian",
    "Natural Language :: Urdu"
    "Topic :: Religion",
    "Topic :: Scientific/Engineering :: Information Analysis"
    "Topic :: Text Processing :: Linguistic",
]
keywords = ["arabic", "persian", "urdu", "quran", "manuscript", "rasm", "unicode", "NLP", "digital humanities"]
requires-python = ">=3.8"
dependencies = [
    'importlib-metadata>=6.6.0',
]

[project.optional-dependencies]
dev = [
    'ujson>=5.7.0',
    "pytest",
]

[project.scripts]
realpython = "rasm.bin.rasm"

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"