[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rasm_arch"
version = "1.2.2"
description = "Rasm_arch is a text processing utility for converting Arabic-scripted text to a completely dediacritised skeleton"
readme = "README.md"
authors = [{ name = "Alicia González Martínez", email = "aliciagm85+rasm_arch@google.com" },
           { name = "Thomas Milo"}]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Natural Language :: Arabic",
    "Natural Language :: Persian",
    "Natural Language :: Urdu",
    "Topic :: Religion",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Text Processing :: Linguistic",
]
keywords = ["arabic", "persian", "urdu", "quran", "manuscript", "rasm", "unicode", "NLP", "digital humanities"]
requires-python = ">=3.8"
dependencies = [
    'importlib-metadata>=6.6.0',
]

[project.optional-dependencies]
dev = [
    'ujson>=5.7.0',
    "pytest",
]

[project.scripts]
rasm_arch = "rasm_arch.bin.rasm-arch"

[project.urls]
"Homepage" = "https://github.com/kabikaj/rasm_arch"

[options]
zip_safe = True
include_package_data = True

[options.package_data]
data = data/*.json
